package jet.opengl.demos.amdfx.shadows;

public enum SHADOWFX_RETURN_CODE {

	SHADOWFX_RETURN_CODE_SUCCESS,
    SHADOWFX_RETURN_CODE_FAIL,
    SHADOWFX_RETURN_CODE_INVALID_DEVICE,
    SHADOWFX_RETURN_CODE_INVALID_DEVICE_CONTEXT,
    SHADOWFX_RETURN_CODE_INVALID_ARGUMENT,
    SHADOWFX_RETURN_CODE_INVALID_POINTER,
    SHADOWFX_RETURN_CODE_D3D11_CALL_FAILED,
    SHADOWFX_RETURN_CODE_D3D12_CALL_FAILED,
}
