package jet.opengl.demos.amdfx.sssr;

public enum FfxSssrStatus {
    FFX_SSSR_STATUS_OK,

    FFX_SSSR_STATUS_INVALID_VALUE,
    FFX_SSSR_STATUS_INVALID_OPERATION,
    FFX_SSSR_STATUS_OUT_OF_MEMORY,
    FFX_SSSR_STATUS_INCOMPATIBLE_API,
    FFX_SSSR_STATUS_INTERNAL_ERROR
}
