package jet.opengl.demos.demos.amdfx.dof;

/**
 * Created by mazhen'gui on 2017/6/24.
 */

public enum DEPTHOFFIELDFX_RETURN_CODE {
    DEPTHOFFIELDFX_RETURN_CODE_SUCCESS,
    DEPTHOFFIELDFX_RETURN_CODE_FAIL,
    DEPTHOFFIELDFX_RETURN_CODE_INVALID_PARAMS,
    DEPTHOFFIELDFX_RETURN_CODE_INVALID_DEVICE,
    DEPTHOFFIELDFX_RETURN_CODE_INVALID_DEVICE_CONTEXT,
    DEPTHOFFIELDFX_RETURN_CODE_INVALID_SURFACE,
}
